### ISSUE TITLE
Inconsistent integer length between Data TotalRowCount and ReaderOptions Count/Offset

### ISSUE THREAD

**Issue by AndyCross** [elastacloud/parquet-dotnet#148]
parquet-dotnet will return a TotalRowCount in the INT64 range. The reader options for offset and count are both INT32. 

This means (for a very long file) the options aren't unable to reach the end of the file, over INT32.MaxValue.

**Comment by aloneguid** [comment]
I hear you. It's rather the other way around, all counters should be `int` not `long`. .NET collections can't hold more than `int.MaxValue` elements.

**Comment by AndyCross** [comment]
Interesting; so what happens in the case of those very long files?

**Comment by aloneguid** [comment]
That got me thinking that it's not going to work. I think the better solution would be to still have `long TotalRowCount` and `int RowCount` which essentially means that users can't read more than `int` at a time. It's a good thing because amount of RAM with rows of `int` count is large anyway.

On the other hand, `offset` and `count` must be `long` so you can still specify where to read from.

You can see this pattern in .NET framework itself, for example `System.IO.Stream` has `long` type for `Position` because you don't hold it in memory, whereas collections hold up to `int` elements.
