### ISSUE TITLE
Writer - remove requirement for seekable stream

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#166]
Although reader must be seekable, writer doesn't suffer from that. However, some changes need to be made as there are a few .Seek calls we use.

This allows to use minimum amount of ram when writing extra large files.

**Comment by mukunku** [comment]
Due to the **Position** getter call below, doesn't this still make the Writer require a Seekable stream? The result of the Position doesn't seem to be used as well. 

`public void Write(DataSet dataSet, CompressionMethod compression = CompressionMethod.Gzip, bool append = false)
      {
         PrepareFile(dataSet, append);

         var stats = new DataSetStats(dataSet);

         int offset = 0;
         int count;
         do
         {
            count = Math.Min(_writerOptions.RowGroupsSize, dataSet.Count - offset);
            Thrift.RowGroup rg = _meta.AddRowGroup();
            long rgStartPos = _output.Position;
            rg.Columns = dataSet.Schema.Elements
               .Select(c =>
                  Write(c, dataSet.GetColumn(c.Name, offset, count), compression, stats.GetColumnStats(c)))
               .ToList();

            //row group's size is a sum of _uncompressed_ sizes of all columns in it, including the headers
            //luckily ColumnChunk already contains sizes of page+header in it's meta
            rg.Total_byte_size = rg.Columns.Sum(c => c.Meta_data.Total_compressed_size);
            rg.Num_rows = count;

            offset += _writerOptions.RowGroupsSize;
         }
         while (offset < dataSet.Count);

         _dataWritten = true;
      }`

I bring this up because I'm unable to write to my Stream which is not seekable.

**Comment by aloneguid** [comment]
@mukunku that's a good point, looking at some stream implementations, they are throwing an exception when calling to `Position`. Although it's not the case with others we've used in testing. I think it's worth raising an issue for this. Which stream are you using at the moment?

**Comment by mukunku** [comment]
I'm using [GZipStream](https://msdn.microsoft.com/en-us/library/system.io.compression.gzipstream.position(v=vs.110).aspx).

I had to wrap the GZipStream class in another class and override the Position getter to return a default value as a workaround for now.

**Comment by aloneguid** [comment]
@mukunku thank you, raised an issue for this #252.

**Comment by aloneguid** [comment]
@mukunku just a thought, Parquet supports gzip compression out of the box, you can pass a compression method as a parameter. You might not need to compress it with GZipStream at all.

**Comment by mukunku** [comment]
@aloneguid I'm very new to Parquet. The reason I didn't use the Gzip compression in the Write method is because I'm streaming a large data set as a Parquet file.

Which means I really have to create a DataSet and add a single row to it then write that to the output stream:` parquetWriter.Write(dataSet, CompressionMethod.None);` in a loop (Since I only  have one row of data in memory at any given time).

So if I enable compression on a single record's Write, it seems only the single record is compressed which ends up increasing the size of the file.

I believe compression needs to be on the page level but how that could be accomplished when I'm writing rows one-by-one I'm not sure.

Any help would be appreciated.

**Comment by aloneguid** [comment]
@mukunku we've got similar problems all over the shop, the simple answer is Parquet is not designed for streaming - it works best when writing in chunks of rows (5'000 seems to be a general advise). 

What we ended up doing in a few projects is keeping DataSet open for some time until there are N number of rows available and flush it in one go with ParquetWriter.Write(), then accumulate next DataSet until there is no data. Here is an example: https://github.com/elastacloud/parquet-usql/blob/master/src/Parquet.Adla/Outputter/DataSetBuilder.cs

In general,  you can write continuously in DataSets with 1 row, however internally that creates a large binary envelope around the row (comparing to the size of the row) and ends up in a large file. Moreover, big data processing platforms (Apache Spark, Impala etc.)  don't seem to handle these file well as unpacking each DataSet results in extra CPU and disk overhead so it becomes extremely slow to read.

**Comment by mukunku** [comment]
@aloneguid thanks for the tip. I'll look into it and see how it affects the output.
