### ISSUE TITLE
Write out in CSV

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#181]
`CsvFormat` supports reading `CSV` into `DataSet`, writing back should be easier to impellent and  useful.

**Comment by AndyCross** [comment]
Parq supports this; why are you putting this in the core lib? To me this is a concern of consumers, otherwise you'll have to do the same with every other format that you think is useful; xml, json, tsql. ... bloat

If you look at the parq implementation, you'll see there is nothing special about it that would be better internal to the library. https://github.com/elastacloud/parq/blob/master/src/parq/Exporters/CsvExporter.cs

**Comment by aloneguid** [comment]
@AndyCross you're right it's not a right place for it. However I think this should be moved to parquet-utils, we haven't got that project set up yet. Utils will add analytics and other stuff on top.

**Comment by AndyCross** [comment]
cool; open this issue in Parq and have it moved out of parq. We shouldn't have two implementations. Also it shouldn't go into Parquet-dotnet to come into parquet-utils, that's silly.

**Comment by aloneguid** [comment]
Moving this out soon to another project.
