### ISSUE TITLE
status of arrow support 🏹

### ISSUE THREAD

**Issue by denfromufa** [elastacloud/parquet-dotnet#335]
I recall some conversation from twitter about Arrow support and also some experiments in this repo. Is there any plan for this support yet? Also I understand that Apache Arrow prefers the development for new languages in their repo.

https://arrow.apache.org/docs/python/parquet.html

**Comment by aloneguid** [comment]
Its definitely in the works, however it's hard to tell when we get any reasonable public beta that is more or less usable. There seems to be more interest in parquet support at the moment than Arrow, therefore it's a bit slow moving. 

I'm personally still struggling to find a good use case for Arrow in .net ecosystem as this is not the first platform of choice in big data world, however could be because I didn't dig deep enough. I'll be interested to hear more use cases why and how you would use it to properly kick this off either here or in Apache repo.

**Comment by xhochy** [comment]
One of the interesting use cases of Arrow for languages that are the major player in the big data world is to connect to this world with nearly no overhead. For example, I'm working myself currently on an JDBC<->Arrow interface in Python. There was a PR to the Arrow repo that provides a JDBC<->Arrow bridge in Java and we have a semi-working in-process (and fully working inter-process) bridge between Arrow-Java and Arrow-C++/Python. This enables me to use JDBC drivers in Python without the overhead of serialisation that normally occurs between the JVM and Python when passing data around. This is very useful as a lot of applications only provide good JDBC drivers but their ODBC or Python support is either non-existing or painfully slow.

For the repo question: It makes very much sense to develop it inside the Arrow repository. We have there really good infrastructure in place to do integration testing between the various Arrow implementations. Ensuring that all implementations work on the exactly same memory format is crucial in the project as we want to avoid memory copies as much as possible and only pass pointers to the respective structures from one language/ecosystem to another.

**Comment by wjrogers** [comment]
I am looking for a .NET implementation of Arrow, too. I have a large existing .NET codebase, and I would like to provide fast, efficient transfer of data to the Python world. Implementing an API over my existing code is a huge timesaver vs re-implementing all those queries and business logic in Python, but I'm currently stuck serializing to CSV or JSON. Pandas is encouraging use of Arrow, and I want to get on board.

**Comment by aloneguid** [comment]
@xhochy @wjrogers sounds really interesting. How do you see the moving parts interacting with each other, would you let's say deploy two processes in different runtimes and somehow connect them? Is there an alternative to Thrift RPC in Arrow (to define method calls between parties)?

**Comment by xhochy** [comment]
Nowadays there is Arrow Flight which builds upon grpc for calls between different process. If you want to do RPC between processes. You could use just any transport layer but the advantage of Flight is that it has some extensions on top of grpc that avoid copies of the heavy Arrow data. Spark for example passes Arrow between Scala-Spark and PySpark simply using their own custom network "protocol". 

In my cases where I pass between Python and Java, I'm actually doing that in-process by using https://jpype.readthedocs.io/en/latest/ . There I construct the Python Arrow structures by taking the memory address of the underlying buffers in Java. The Python objects then access the same memory as the Java ones. They also holds a reference to the main Java objects so that those are not garbage collected.

**Comment by denfromufa** [comment]
@xhochy  i think your approach with jpype and arrow would make a lot of sense for pythonnet too:

https://github.com/pythonnet/pythonnet/issues/514

**Comment by xhochy** [comment]
There is now a C# implementation for Apache Arrow: https://github.com/feyenzylstra/apache-arrow Have not yet had time to look into it.

**Comment by aloneguid** [comment]
I think it's OK, has some good ideas around efficiency. It's far from being production ready though. I'm still struggling at the moment with a use-case, maybe it's the way I'm personally approaching a problem. Parquet.Net was created around a business case, and we don't have one at the moment with Arrow. Internally we can marshal data between python machine learning libraries and .NET runtime, however that's not really useful as there is no big requirement for speed (we're just picking up computation result once an hour or so, it's hard to justify why not just use JSON).

I'd see Arrow's use case at the moment if say we could host .NET Core runtime inside Spark and marshal between .net and java, just like PySpark does? I'm trying to investigate how much effort it is to add another language there.

**Comment by xhochy** [comment]
For the Spark case, you could either look at the PRs by Bryan Cutler to (Py)Spark or the current work that is done for R<->Spark serialization in https://github.com/rstudio/sparklyr/pull/1611

**Comment by denfromufa** [comment]
Another official implementation here and related discussion:

https://github.com/apache/arrow/tree/master/csharp

DataFrame for .NET Core Discussion:
https://github.com/dotnet/corefx/issues/26845

**Comment by aloneguid** [comment]
Thanks all, it's been extremely useful. I'll be watching the space and publish something on Arrow in future.

**Comment by EraYaN** [comment]
So since this issue was closed the Apache Arrow project has added [a package to NuGet](https://www.nuget.org/packages/Apache.Arrow/). I think this can replace most if not all of the SharpArrow namespace in the current project. And this should enable reading parquet columns directly into Arrow buffers. Which would be very neat for larger data sizes and interoperability.

**Comment by aloneguid** [comment]
@EraYaN yes correct, that package seems to be OK, and Microsoft is using it in .NET for Apache Spark implementation. I can't see a reason to create our own.
