### ISSUE TITLE
Can parquet-dotnet be use to serialize a Web API response?

### ISSUE THREAD

**Issue by bryanjhogan** [elastacloud/parquet-dotnet#366]
Question - 

Can parquet-dotnet be use in Web API to serialize responses? 

I am wondering if it can be use like protobuf, messagepack or any other format.

**Comment by aloneguid** [comment]
You can definitely do that, however it won't be very effective. Where parquet really shines is querying relatively large amounts of data. In fact, parquet stores it's own metadata in the file in Thrift format (similar to protobuf). Writing parquet is CPU intensive due to logical and physical compression.


For general purpose web API i'd go for protobuf or thrift (although later is poorly supported/designed on .net as I found out when building parquet). You can also look at Google Flatbuffers if speed is an issue, it's used in Apache Arrow and is generally faster than Thrift. Protobuf has excellent tooling for IDEs like VS and good fast libraries (see [protobuf-net](https://github.com/mgravell/protobuf-net)).

**Comment by aloneguid** [comment]
@bryanjhogan yes makes perfect sense, I just checked that we don't actually rely on generics internally, it's only used in public method signature, so adding an overload should be trivial.

**Comment by bryanjhogan** [comment]
That would be a helpful addition to the `ParquetConvert` class.

**Comment by aloneguid** [comment]
will be fixed as a part of bigger issue
