### ISSUE TITLE
Exception thrown when trying to initialize ParquetReader from MemoryStream

### ISSUE THREAD

**Issue by murick** [elastacloud/parquet-dotnet#390]
**Version:** Parquet.Net v. 3.2.5

**Runtime Version:** .Net Framework v 4.6.1

**OS:** Windows 10 x64

#### Expected behavior
I am trying writing a parquet parsing module for the existing environment. I am given a string (contents of the parquet file) and I have to represent it in a JSON format. I am converting this string into bytes array, then create a memory stream from it and initialize the ParquetReader. 

[result.parquet.txt](https://github.com/elastacloud/parquet-dotnet/files/2750835/result.parquet.txt)
```csharp
static void Main(string[] args)
 {
     // string may be created in another way
     // i.e. using System.IO.File.ReadAllText
     using (StreamReader sr = new StreamReader("C:\\path\\to\\file\\result.parquet"))
     {
         string text = sr.ReadToEnd();
         TryParse(text, out var jsonValue);
         System.Console.WriteLine(jsonValue.ToString());
     }
}

public static bool TryParse(string value, out JToken json)
 {
     using (Stream memStream = new MemoryStream(Encoding.UTF8.GetBytes(value)))
     {
          // works OK with Stream fileStream = System.IO.File.OpenRead("result.parquet")
          using (var parquetReader = new Parquet.ParquetReader(memStream))
          {
              …
          }
     }
     return json != null;
}     
```

#### Actual behavior

The program throws out exceptions every time it reaches the ParquetReader initialization. Interesting thing is that it throws different exceptions depending on the parquet file contents. This is what I usually get:

```csharp
Thrift.Protocol.TProtocolException
  HResult=0x80131500
  Message=Exception of type 'Thrift.Protocol.TProtocolException' was thrown.
  Source=Parquet
  StackTrace:
   at Parquet.Thrift.FileMetaData.Read(TProtocol iprot)
   at Parquet.File.ThriftStream.Read[T]()
   at Parquet.ParquetActor.ReadMetadata()
   at Parquet.ParquetReader..ctor(Stream input, ParquetOptions parquetOptions, Boolean leaveStreamOpen)
   at ParquetReader.Program.TryParse(String value, JToken& json) in C:\Users\USER\source\repos\ParquetReader\ParquetReader\Program.cs:line 32
   at ParquetReader.Program.Main(String[] args) in C:\Users\USER\source\repos\ParquetReader\ParquetReader\Program.cs:line 160
```
Note, this happens only when I use MemoryStream. There's no issue if I use FileStream.

**Comment by aloneguid** [comment]
Parquet is not a text format so you can't read it in a string. Use File.OpenRead or other alternative which allows direct accces to file content.

**Comment by murick** [comment]
Hello Ivan,

Thank you for the prompt response. Correct me please if I'm wrong, but I did not provide a string to the ParquetReader constructor. I used MemoryStream instead. The main requirement I got is to read from string (the file parsing and extraction is done in a separate module that is outside of my scope).

**Comment by aloneguid** [comment]
Other than its extremely ineffective its just not going to work. You can't transform a random byte array in a string, and even if you can in some cases, it won't come out as the same byte array back because of special bytes strings just don't handle.

Your string either has to contain encoded byte array (base 64 for instance) so you can decode it back or don't use strings at all, which would be a good decision. Just don't use strings in application logic. They are bad. They pressure GC and copy memory unnecessary badly. Encoding and decoding kills CPU for no reason. And don't even get me started on GC gen 3 pressure and LOH, it's a big headache. The purpose of strings is to represent information to the user, not be part of any logic. This is outside of parquet library scope. 

I think you should raise the issue with HR and fire the person who came up with an idea to pass binary data in strings. Elastacloud provides great development and consultancy services by the way.
