### ISSUE TITLE
Question: is partial column extract possible?

### ISSUE THREAD

**Issue by murick** [elastacloud/parquet-dotnet#399]
Hello,

I have a question regarding the partial data extraction. Here's my scenario:

I have a huge (1.5 - 2Tb) parquet file in the Azure Blob Container and I am given a stream to that file. The requirement is to extract _N_ rows from that file. It does not have to be same _N_ rows across all columns. For instance, it is acceptable to have top 10 row values for the first column, and then random 10 ones for remaining columns. 
Question: is there a way to extract only portion of values (something similar as Spark does) without reading the entire column? Something like `DataColumn ReadColumn(DataField field, int start, int count)` method.

Thank you in advance.

**Comment by murick** [comment]
Thank you for the quick response. Pardon my ignorance, but isn't the number of rows in a row group somewhat read only? I mean can I actually adjust number of rows in a group, as well as total number of groups in a parquet file when reading it from a stream?

**Comment by murick** [comment]
Didn't mean to be too verbose, just wanted to describe my example clear:

So, there's a parquet file in the Azure Blob Container. I don't know anything about the file contents beforehand, i.e. number of row-groups, their sizes, etc. I have to iterate through the columns and for each one, extract _N_ rows. This _N_ might be different from what is contained in a row-group. 

Now I want to get only desired portion of a column without reading the entire column itself. If group reader provides a feature like this - `DataColumn ReadColumn(DataField field, int start, int count)` - then problem is solved. If it only allows reading all contents of a particular column, then I'd check if it can stream it. If yes, then I can break the iteration after _N_ values and then skip to the next column in the row-group. If streaming is not an option either, then I guess I have to read the entire row-group into memory. (I'm not sure how big it can be)

**Comment by aloneguid** [comment]
First parquet reader goes to the end of the file where there is sort of a map where particular bits are located. The reasom it's at the end is its only fully constructed when while file is written. Therefore you need to be able to fast forward the stream to the end without reading the entire file. Parquet Reader in this lib assumes that input stream is seekable which is not true for a network stream or Azure blob stream, therefore you want to create some wrapper with caching etc that downloads requested blocks from blob storage as stream is seeked. This is not a 5 min exercise but achievable. 

Once this is achieved reader knows where to open tow groups and columns. However it can only read entire column from a single row group as a minimum. The reason is columns are compressed both logically and physically, there is no way to make partial read. Any api in Spark that reaturn a subset simply read entire colum and discard the remaining data.

**Comment by murick** [comment]
Thank you for the detailed explanation.

**Comment by aloneguid** [comment]
If you're interested in a seekable azure blob stream I've opened an issue in another repo I maintain, you can track it here: aloneguid/storage#55. Closing this one.

**Comment by murick** [comment]
Sounds great, thank you!

**Comment by andrei-faber** [comment]
@aloneguid it still would be useful to read the column in chunks rather than in one huge array, i.e. something like `groupReader.ReadColumn(dataField, buffer, count)`
