### ISSUE TITLE
Large groups with timestamp data are not read correctly

### ISSUE THREAD

**Issue by alexebl** [elastacloud/parquet-dotnet#400]
**Version:** 

**Runtime Version:** .Net Framework v, .Net Core v etc.

**OS:** Windows

#### Expected behavior

I generate a parquet file with a commercial system for data acquisition.
This file has about 1.7 million rows and contains a time column represented by 64bit int format. The group size inside this file is 400773, what I think is source of the problem. 
The time column contains continuous timestamp with 1ms resolution.

#### Actual behavior

ParquetRowGroupReader reads only the first 131072 = 2^17 timestamps correct while the remaining values of this group are set to a constant value which is equal to the first value of the coresponding group.
This behaviour affects only this time column, which is also the first one in the table, other columns with numeric data are correct. 
I checked the data also with spark, here the time values are correct.  

### Steps to reproduce the behavior

[TestDataSet.zip](https://github.com/elastacloud/parquet-dotnet/files/2821130/TestDataSet.zip)
![timeplot](https://user-images.githubusercontent.com/47241906/52117452-0ebd5000-2614-11e9-82d8-4e19c58705ce.png)

#### Code snippet reproducing the behavior

```csharp
//here
```

**Comment by CurtHagenlocher** [comment]
The column group contains a dictionary page followed by four pages of data. The first data page has an encoding of PLAIN_DICTIONARY, which means that it references the data in the dictionary. The other data pages have encodings of PLAIN, which means that they do not.

But the constructor of DataColumn seems to make the assumption that if there's a dictionary, then all of the data pages reference the dictionary. That is not true in this case. The data from "definedData" needs to be merged somehow with the data from "dictionary". The best way to do this is probably to change DataColumnReader.ReadColumn so that in the PLAIN encoding case the indexes array is initialized with -1 to mean "use the plain data instead of the dictionary data".

Another oddity I noticed is that the dictionary is allocated enough space to hold the entire row group's worth of data even though it really only seems to need to hold the dictionary data itself. This means using Num_values from the dictionary page header instead of NumValues from the column metadata in order to initialize the array size.

**Comment by CurtHagenlocher** [comment]
I've submitted a pull request to fix this bug.

**Comment by aloneguid** [comment]
closing as fixed by @CurtHagenlocher
