### ISSUE TITLE
Writer produces unreadable files when writing DateTimeOffset

### ISSUE THREAD

**Issue by aloneguid** [elastacloud/parquet-dotnet#83]
I think it doesn't annotate it properly. As a part of this create integration test which writes one type and one value and reads it in full, going through the whole lifecycle. Unit tests for this succeed btw.

**Comment by azurecoder** [comment]
picking this up today

**Comment by aloneguid** [comment]
@azurecoder great thanks )

**Comment by azurecoder** [comment]
investigating now - made all the alterations to ensure that we write EXACTLY the same way as we read but Spark uses an INT96 first 8 bytes nanos, last 4 date in Julian time. I have a small issue now:

TIMESTAMP_MILLIS can only annotate INT64

So I think there is something missing as well - doing all of the necessary checks - currently we don't support the INT64 timestamp millis because Spark won't write in this way until 2.2 is released. Will keep investigating probably something small.

**Comment by azurecoder** [comment]
Okay, my mistake, schema shows INT96 type annotating UTF8 only issue is that it's not really an INT96 - this is how we interpret it but Spark writes it out as a binary type but of a fixed 12 byte len.

UTF8 can only annotate binary fields

Yuck. We have to support this but I will raise another 2 issues to support INT64 TIMESTAMP_MILLIS and also the INTERVAL type which Spark will support from 2.2.

**Comment by aloneguid** [comment]
@azurecoder yes the parquet specs says:

```
DATE - INT32 (up to day precision)
TIME_MILLIS - INT32 (time only)
TIMESTAMP_MILLIS - INT64 (up to second precision)
INTERVAL - INT96 (full precision)
```

At the moment DateTimeOffset maps to INT64 only because it's easy to implement, but it cuts off milliseconds. This is not perfect but fine for current client ;) Ideally when we write DateTimeOffset that should map to INT96. The reader though has to be able to read anything and map back to DateTimeOffset. That is my understanding at the moment.

**Comment by azurecoder** [comment]
Agreed. They have changed the code in Spark 2.2 but represent this correctly.

```
.required(INT32).as(DATE).named("date") 
.required(INT32).as(TIME_MILLIS).named("time") 
.required(INT64).as(TIMESTAMP_MILLIS).named("timestamp") 
.required(FIXED_LEN_BYTE_ARRAY).length(12).as(INTERVAL).named("interval") 
```
but the last item currently is treated as a TIMESTAMP_MILLI rather than an interval. I will update this and fix this current issue but agreed all of the existing variations and future need to be supported. I have raised issues for them now.

**Comment by azurecoder** [comment]
Closing as complete now. Supporting other date formats in other issues.
